### ISSUE TITLE
The Package did not load correctly

### ISSUE THREAD

**Issue by Maik-Robin** [RandomEngy/UnitTestBoilerplateGenerator#13]
### Installed product versions
- Visual Studio: 2017 Express
- This extension: Unit_Test_Boilerplate_Generator_v2.5.5

### Description
The following error message is showing up

![image](https://user-images.githubusercontent.com/43937967/129702849-bd650e3e-0eec-4f19-8d15-5ed81f056bd0.png)

### Steps to recreate
1. Install Extension
2. Start Visual Studio

### Current behavior
Error Message displayed

**Comment by RandomEngy** [comment]
I uploaded a new version 2.5.6 that reworks how the packages are loaded. Give it a shot.

**Comment by RandomEngy** [comment]
Re open if you're still having issues.
