### ISSUE TITLE
Update for Visual Studio 2022

### ISSUE THREAD

**Issue by oluciano** [RandomEngy/UnitTestBoilerplateGenerator#14]
### Installed product versions
- Visual Studio: [2019 Enterprise]

### Description

Was wondering if there are plans to update this extension for VS 2022? Migration guide can be found here: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension

**Comment by RandomEngy** [comment]
I've gotten the email exhorting me to update my extension. I'm planning on it but will need to scrape together the time to do it.

**Comment by oluciano** [comment]
I'm looking forward to receiving updates

**Comment by RandomEngy** [comment]
I just uploaded 2.5.6, which should support VS 2022.
