### ISSUE TITLE
Unable to create unit test classes always errors

### ISSUE THREAD

**Issue by vgwizardx** [RandomEngy/UnitTestBoilerplateGenerator#17]
### Installed product versions
- Visual Studio:  2019
- This extension: 2.5.7

### Description
I just installed 2.5.7 this is on a new computer so didn't have a previous version installed. When I try to generate a unit test I get the following error. 
![image](https://user-images.githubusercontent.com/1323841/134778899-f830c681-437d-4cd7-b2b2-d4079b73c80a.png)
This happens even on projects that have used the boilerplate in the past.

### Steps to recreate
1. Install Unit Test Boilerplate Generator 2.5.7
2. click on a file to generate a test
3. use any settings and click create unit test class
4. get the above error

### Current behavior
Unable to create unit test class

### Expected behavior
Able to create unit test class

**Comment by 304NotModified** [comment]
Do you have a repo to reproduce the issue? I guess it depends of the kind file/project

**Comment by vgwizardx** [comment]
I just created a .net core 3.1 web api project that has the weatherforecastcontroller.cs in it and I get the same error. I have tried reinstalling because it doesn't look like it had to do with the code.

**Comment by vgwizardx** [comment]
Got it working I needed to update to the latest version of visual studio.
