### ISSUE TITLE
Generate files as UTF8-BOM

### ISSUE THREAD

**Issue by a-jackson** [RandomEngy/UnitTestBoilerplateGenerator#2]
### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [2.5.0]

### Description
We're using StyleCop which has a rule that all files should be UTF8-BOM [SA1412](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1412.md).

The files this creates are just UTF8 and so I get a violation for every file generated and have to change it. Would it be possible to change the encoding or add an option for it?

**Comment by RandomEngy** [comment]
I'll change the encoding to include the BOM.

**Comment by RandomEngy** [comment]
Included in the just-released v2.5.4.
