### ISSUE TITLE
Wiki "Custom Format Tokens" redirect to Microsoft's repository

### ISSUE THREAD

**Issue by 304NotModified** [RandomEngy/UnitTestBoilerplateGenerator#20]
### Description
The link on the home page of the wiki redirects to the wrong repo

### Steps to recreate
Click on the link on https://github.com/RandomEngy/UnitTestBoilerplateGenerator/wiki

![image](https://user-images.githubusercontent.com/5808377/134785462-c90eb3ba-084f-4117-8b80-3bbdf5e8bb9b.png)

### Current behavior
Redirects to: [https://github.com/**Microsoft**/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens](https://github.com/Microsoft/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens)

### Expected behavior
Should redirect to: [https://github.com/**RandomEngy**/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens](https://github.com/RandomEngy/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens)

**Comment by RandomEngy** [comment]
Thanks for the report!
