### ISSUE TITLE
Jetbrains Rider support

### ISSUE THREAD

**Issue by PeterKneale** [RandomEngy/UnitTestBoilerplateGenerator#26]
### Current behavior
Supports Visual Studio 

### Desired behavior
Supports Visual Studio and *Rider*

This is a very useful extension, could it be extended to support JetBrains Rider, same functionality, but just adapted to the Rider plugin ecosystem in addition to the Visual Studio Extension ecosystem.

Thanks!

**Comment by RandomEngy** [comment]
I won't be doing that work as I am busy with too many other projects and I don't use Rider. You are welcome to give it a shot.

**Comment by PeterKneale** [comment]
Fair enough 👍
