### ISSUE TITLE
Feature Request: Support blazor unit testing

### ISSUE THREAD

**Issue by dsoltesz** [RandomEngy/UnitTestBoilerplateGenerator#28]
### Description
Would like to see unit test generation that works with blazor and bUnit

**Comment by RandomEngy** [comment]
It sounds like bUnit isn't a separate unit testing framework; it relies on NUnit, xUnit or MSTest, all of which are supported by Unit Test Boilerplate generator. What exactly are you looking for in terms of Blazor support?

**Comment by dsoltesz** [comment]
That it stubs out the test context correctly via bunit so that your blazor code can be tested.
________________________________

**Comment by RandomEngy** [comment]
Could you give an example class file and desired generated test file?
