### ISSUE TITLE
Need to add support for ARM64 versions of Visual Studio.

### ISSUE THREAD

**Issue by thalter** [RandomEngy/UnitTestBoilerplateGenerator#31]
Extension currently won't install on ARM64 version of Visual Studio 2022.

**Comment by RandomEngy** [comment]
I don't have arm64 hardware to test on but it's already targeting Any CPU. I just added arm64 as a target, does this one work?

https://engy.us/misc/UnitTestBoilerplate.vsix

**Comment by thalter** [comment]
Yes, that works! Thanks for the fast turnaround!

**Comment by RandomEngy** [comment]
Released as 2.7.3 on the Marketplace.
