### ISSUE TITLE
List valid tokens links to archived RandomEngy wiki

### ISSUE THREAD

**Issue by mlafleur** [RandomEngy/UnitTestBoilerplateGenerator#34]
### Installed product versions
- Visual Studio: 2022 Enterprise
- This extension: 2.73

### Description
The "List valid tokens" link in the settings dialog redirects to the wiki in the archived RandomEngy wiki.

### Current behavior
Links to https://github.com/Microsoft/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens

### Expected behavior
Should ink to https://github.com/RandomEngy/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens

**Comment by RandomEngy** [comment]
Thanks for the report. Fixed in 2.7.4.
