### ISSUE TITLE
Customize Template But No Change

### ISSUE THREAD

**Issue by serefaltindal** [RandomEngy/UnitTestBoilerplateGenerator#35]
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.7.6

Even if I customize the template, the change is not reflected when I create new unit tests.

![image](https://github.com/RandomEngy/UnitTestBoilerplateGenerator/assets/6718381/d076bed0-60be-46dc-910b-bb3edf3b52ab)

No Change;

The default test template comes

**Comment by RandomEngy** [comment]
Does the Test Framework and Mock Framework you chose when you created the test match the one on this page?
