### ISSUE TITLE
Changing settings has no effect

### ISSUE THREAD

**Issue by VILLAN3LL3** [RandomEngy/UnitTestBoilerplateGenerator#4]
### Installed product versions
- Visual Studio: 2019 Enterprise 16.9.4
- This extension: 2.3.5

### Description
I changed some settings in Tools -> Options -> Unit Test Boilerplate Generator, e. g.: 
Custom mock field declaration format: `private $CustomMockClass$ _mock$InterfaceMockName$;` but the changed settings have no effect on the created boilerplate code.

### Steps to recreate
Install Unit Test Boilerplate Generator extension
Move to Tools -> Options -> Unit Test Boilerplate Generator
Change settings,  e. g.: 
Custom mock field declaration format: `private $CustomMockClass$ _mock$InterfaceMockName$;`
Create new test class using the extension

### Current behavior
The extension settings are ignored

### Expected behavior
The extension settings should be used

![2021-04-27_14h56_50](https://user-images.githubusercontent.com/39371377/116245020-cd6f6880-a768-11eb-91ff-13a491d71be3.png)
![2021-05-01_10h06_33](https://user-images.githubusercontent.com/39371377/116775754-fba0c100-aa64-11eb-83c2-20eb6c1e20dd.png)

**Comment by RandomEngy** [comment]
That's the format for custom mock implementations. Try editing the Test File Contents page.

**Comment by VILLAN3LL3** [comment]
@RandomEngy Yes I also changed settings on the "Test File Contents" page but without effect:
![2021-05-01_10h04_43](https://user-images.githubusercontent.com/39371377/116775730-cf854000-aa64-11eb-8b55-e5326404d636.png)
![2021-05-01_10h05_05](https://user-images.githubusercontent.com/39371377/116775739-dc099880-aa64-11eb-8e49-4ccd18f0f076.png)

**Comment by RandomEngy** [comment]
It looks like you are altering the settings for a different test framework. Pick the NUnit test framework at the top.

**Comment by VILLAN3LL3** [comment]
Hmpf ... oh yes you are right. I completely overlooked that. I apologize for the inconvenience.
