### ISSUE TITLE
Why is the main branch dependabot/nuget/Sandbox/NUnitUwpTestCases/Microsoft.NETCore.UniversalWindowsPlatform-5.4.2?

### ISSUE THREAD

**Issue by 304NotModified** [RandomEngy/UnitTestBoilerplateGenerator#7]
It's a bit confusing ;)

![image](https://user-images.githubusercontent.com/5808377/127854871-f52e48e0-358a-4d2f-9987-c4eb8dc64040.png)

**Comment by 304NotModified** [comment]
Also there are changes in dependabot/nuget/Sandbox/NUnitUwpTestCases/Microsoft.NETCore.UniversalWindowsPlatform-5.4.2 that are not in master and visa versa

**Comment by RandomEngy** [comment]
I had to change repositories and it must have screwed that part up. I switched the default back to "master". Will look at the commit history.

**Comment by RandomEngy** [comment]
What changes are not in master? The last commit on the dependabot branch looks like it's very old.

**Comment by 304NotModified** [comment]
This one, I think it's still valid: https://github.com/RandomEngy/UnitTestBoilerplateGenerator/pull/8
